const SET_MESSAGE = 'SET_MESSAGE'
const SET_AUTH = 'SET_AUTH'
const REMOVE_AUTH = 'REMOVE_AUTH'
const AXIOS_CATCH = 'AXIOS_CATCH'
const SET_DATA = 'SET_DATA'
const SET_SELECTED = 'SET_SELECTED'
const SET_FILES = 'SET_FILES'
const PUSH_DATA = 'PUSH_DATA'
export {
  SET_MESSAGE,
  SET_AUTH,
  REMOVE_AUTH,
  AXIOS_CATCH,
  SET_DATA,
  SET_SELECTED,
  SET_FILES,
  PUSH_DATA
}
